# Generated by Django 4.2 on 2023-04-25 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], default='RS', max_length=2),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='obs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
