# Generated by Django 4.2 on 2023-05-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria_servico', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categoria Serviço',
                'verbose_name_plural': 'Categorias Serviços',
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('preco_marketing', models.FloatField(verbose_name='Preço')),
                ('preco_marketing_promocional', models.FloatField(default=0, verbose_name='Preço Promo')),
                ('categoria_servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='servico.categoriaservico')),
            ],
        ),
    ]
