# Generated by Django 4.2 on 2023-04-21 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInferior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria_inferior', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaSuperior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria_superior', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_marca', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255)),
                ('cod_barras', models.CharField(max_length=13)),
                ('referencia', models.CharField(max_length=50)),
                ('descricao_curta', models.TextField(max_length=255)),
                ('descricao_longa', models.TextField(max_length=255)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos_imagens/%Y/%m/')),
                ('slug', models.SlugField(unique=True)),
                ('preco_marketing', models.FloatField()),
                ('preco_marketing_promocional', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('V', 'Variacao'), ('S', 'Simples')], default='V', max_length=1)),
                ('categoria_inferior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.categoriainferior')),
                ('categoria_superior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.categoriasuperior')),
                ('nome_marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.marca')),
            ],
        ),
    ]
