# Generated by Django 4.2 on 2023-04-24 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_variacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriainferior',
            options={'verbose_name': 'Categoria Inferior', 'verbose_name_plural': 'Categorias Inferiores'},
        ),
        migrations.AlterModelOptions(
            name='categoriasuperior',
            options={'verbose_name': 'Categoria Superior', 'verbose_name_plural': 'Categorias Superiores'},
        ),
        migrations.AlterModelOptions(
            name='variacao',
            options={'verbose_name': 'Variação', 'verbose_name_plural': 'Variações'},
        ),
    ]
