# Generated by Django 4.2 on 2023-04-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_categoriainferior_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='cod_barras',
        ),
        migrations.AddField(
            model_name='variacao',
            name='cod_barras',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
