# Generated by Django 4.2 on 2023-04-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_produto_cod_barras_variacao_cod_barras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='referencia',
        ),
        migrations.AddField(
            model_name='variacao',
            name='referencia',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
