# Generated by Django 4.2 on 2023-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_remove_produto_referencia_variacao_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('V', 'Variável'), ('S', 'Simples')], default='V', max_length=1),
        ),
    ]
