# Generated by Django 4.2 on 2023-04-26 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_alter_produto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriainferior',
            name='categoria_superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.categoriasuperior'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing',
            field=models.FloatField(verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_marketing_promocional',
            field=models.FloatField(default=0, verbose_name='Preço Promo'),
        ),
    ]
